name: app_mvvm_getx
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  intl: ^0.18.1
  flutter_localizations: # Dette er den korrekte nøgle for Flutter lokalisering
    sdk: flutter # Bemærk at flutter_localizations er en del af Flutter SDK

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_utils: ^2.8.7 # Dette værktøj hjælper med at generere lokaliseringsfiler fra .arb filer

flutter:
  uses-material-design: true
  # Tilføj eventuelle nødvendige aktiver og skrifttyper her

  # For at understøtte lokaliseringsfiler, kan du tilføje en konfiguration for at generere kode
  # baseret på dine .arb filer. Dette er dog valgfrit og afhænger af, hvordan du vælger
  # at håndtere lokaliseringsprocessen:
  generate: true
